#!/bin/bash
echo " ==== "
echo " Proudly powered by Maximilien Levesque and PersonalHPC "
echo " Comments, bug-reports : contact@personalhpc.com"
echo " ==== "

# be sure you have all necessary software
sudo apt-get install git autoconf automake libtool gfortran g++ flex make -y

# grab last version of openmpi, compile it, and move it to /opt/openmpi/bin and /opt/openmpi/lib
ici=$PWD
git clone https://github.com/open-mpi/ompi.git
cd ompi
./autogen.pl
mkdir _mybuild
cd _mybuild
#../configure --prefix=$ici/ompi/_mybuild/_myinstall --exec-prefix=$ici/ompi/_mybuild/_myinstall-exec --with-platform=optimized
../configure --prefix=/opt/ompi --exec-prefix=/opt/ompi
make all install
sudo mkdir -p /opt/openmpi/lib /opt/openmpi/bin
sudo cp -rf install-exec/lib/* /opt/openmpi/lib/.
sudo cp -rf install-exec/bin/* /opt/openmpi/bin/.
sudo cp -rf install/include/mpi.h /opt/openmpi/lib/.
# at this point, we have everything needed in /opt/openmpi

# grab last version of lammps
git clone https://github.com/lammps/lammps lammps
cd lammps/src
# compile packages that you need. This is user-specific. Here that's OK for what I am aware you typically use.
make yes-asphere yes-body yes-class2 yes-colloid yes-dipole yes-fld yes-granular yes-kspace yes-manybody yes-mc yes-misc yes-molecule yes-mpiio yes-opt yes-peri yes-replica yes-rigid yes-shock yes-snap yes-srd yes-xtc
wget "https://raw.githubusercontent.com/personalhpc/LAMMPS-Makefile-for-PersonalHPC/master/Makefile.personalhpc" && mv Makefile.personalhpc MAKE/MACHINES/.  # proudly powered by Maximilien Levesque, for PersonalHPC
make -j16 personalhpc
cd .. && mkdir -p _mybuild && mv src/lmp_personalhpc _mybuild/lammps

echo "... OK. Everything's fine"
echo "Your LAMMPS executable is $ici/lammps/src/lammps"
echo "      "
echo " ==== "
echo " Proudly powered by Maximilien Levesque and PersonalHPC "
echo " Comments, bug-reports : contact@personalhpc.com"
echo " ==== "

# LAMMPS is now compiled. It is called mylammps and can be found in mylammps/src/.

# comment: If you are not certain MPI tasks are being bound (check the defaults for your MPI installation), binding can be forced with these flags:
# OpenMPI 1.8: mpirun -np 2 -bind-to socket -map-by socket ./lmp_openmpi ...
